# Generated by Django 5.2.4 on 2025-07-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('langue_principale', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=50)),
                ('numero_passeport', models.CharField(max_length=50)),
                ('date_expiration_passeport', models.DateField()),
                ('statut_marital', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.TextField()),
                ('ville_residence', models.CharField(max_length=100)),
                ('quartier_residence', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('pays_etudes', models.CharField(max_length=100)),
                ('ecole_provenance', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=50)),
                ('diplome_universite', models.CharField(max_length=100)),
                ('diplome_langue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=255)),
                ('filieres', models.ManyToManyField(related_name='ecoles', to='student.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.filiere')),
            ],
        ),
    ]
